services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@2024
    ports:
      - "1433:1433"
    networks:
      - interview_network
    volumes:
      - sql_data:/var/opt/mssql

  webapi:
    build: 
      context: ./interviewProject
      dockerfile: Dockerfile
    container_name: interview_project
    environment:
      - SQL_CONNECTION_STRING=Server=sqlserver,1433;Database=InterviewDb;User Id=sa;Password=Password@2024;TrustServerCertificate=true;
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8086:80"
    networks:
      - interview_network
    depends_on:
      - sqlserver

networks:
  interview_network:

volumes:
  sql_data: